name: gnr_project_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch>=2.3.0
    - torchvision
    - transformers>=4.49.0
    - accelerate>=0.30.0
    - qwen-vl-utils
    - pillow
    - pandas
    - tqdm
